Stephensbranch
lyndseyjw/natural-disaster-relief pull request #19
Opened 2021-08-27 21:56 UTC by stephenryan183

was working on the read me

2021-08-28 03:56 UTC, Kasdjono requested changes
<img width="1258" alt="Screen Shot 2021-08-27 at 8 55 36 PM" src="https://user-images.githubusercontent.com/56100654/131205429-17118f40-81d5-424d-818a-1f9d2e1cf575.png">

2021-08-30 04:40 UTC, stephenryan183 reviewed
nice

2021-08-30 04:46 UTC, Kasdjono approved these changes

2021-08-30 04:46 UTC, merged

2021-08-30 04:53 UTC, stephenryan183 reviewed
nice